org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=soaring_phantoms
mod.name=Soaring Phantoms
mod.group=me.pajic
mod.version=1.2.8
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Replaces vanilla's terrible phantom spawning rules with an altitude-based approach
mod.sources_url=https://github.com/pajicadvance/soaring-phantoms
mod.homepage_url=https://modrinth.com/mod/soaring-phantoms
mod.issues_url=https://github.com/pajicadvance/soaring-phantoms/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=d4Rp6J8P
publish.curseforge=1022172
publish.github=false
